class MAU_Config:
    def __init__(self):
        self.model_config = {
            'scheduled_sampling': 1,
            'sampling_stop_iter': 50000,
            'sampling_start_value': 1.0,
            'sampling_changing_rate': 0.00002,
            'num_hidden': '64,64,64,64',
            'filter_size': 5,
            'stride': 1,
            'patch_size': 1,
            'layer_norm': 0,
            'sr_size': 2,
            'tau': 5,
            'cell_mode': 'normal',
            'model_mode': 'normal',
            "learning_rate": 1e-03,
            "initial_lr": 1e-02,
            "lr_min": 1e-06,
            "batch_size": 16,
            "drop_path" : 0.1,
            "drop":0.0,
            "optimizer": "adam",
            "weight_decay": 0.0,
            "k_decay": 1.0,
            "scheduler": "cosine",
            "warmup_t" : 0, 
            "warmup_lr_init": 1e-05,
            "warmup_epoch": 0,
            "loss_function": "mse",
        }